### ISSUE TITLE
how to get oodle xor and oodle_state from another lost ark server

### ISSUE THREAD

**Issue by Yuandiaodiaodiao** [lost-ark-dev/meter-data#3]
sorry to disturb
i'm playing lost ark china server(tencent) (it was opened at 2023.7.20)  
and i found that  it' network package has same structure  but use different oodle xor
the network package also has opcode , data , xor and compression
but opcode is difference to another lost ark server (such as player death'opcode is 38989 in china lost ark)

can i only compare between two server's network package and resolve the new oodle_state ?
or i have to  do reverse engineering to the game client ?

**Comment by Herysia** [comment]
Idk for china, but it's probably diff structs each patch like in aws. So you'll need to patch the packet structure every time they change (see meter core updates to have an idea of the kind of changes required

**Comment by molenzwiebel** [comment]
oodle_state is in the lpk files, the xor key can be computed from connecting to the servers; shalzuth has a very messy implementation for both: https://github.com/shalzuth/LostArkDumper

**Comment by YinBuLiao** [comment]
> > oodle_state is in the lpk files, the xor key can be computed from connecting to the servers; shalzuth has a very messy implementation for both: https://github.com/shalzuth/LostArkDumper
> 
> good ! thank you , it may helps my a lot. i have recompile oo2net_9_win64.ll to ge oodle_state. only one XOR need to resolve

Have you finished making the Chinese version of the DPS plug-in?

**Comment by Yuandiaodiaodiao** [comment]
> > > oodle_state is in the lpk files, the xor key can be computed from connecting to the servers; shalzuth has a very messy implementation for both: https://github.com/shalzuth/LostArkDumper
> > 
> > 
> > good ! thank you , it may helps my a lot. i have recompile oo2net_9_win64.ll to ge oodle_state. only one XOR need to resolve
> 
> Have you finished making the Chinese version of the DPS plug-in?

i do ，but i use a very hack way ， it seems like a cheating program. i change the game files

**Comment by qhhuang** [comment]
> > > > oodle_state is in the lpk files, the xor key can be computed from connecting to the servers; shalzuth has a very messy implementation for both: https://github.com/shalzuth/LostArkDumper
> > > 
> > > 
> > > good ! thank you , it may helps my a lot. i have recompile oo2net_9_win64.ll to ge oodle_state. only one XOR need to resolve
> > 
> > 
> > Have you finished making the Chinese version of the DPS plug-in?
> 
> i do ，but i use a very hack way ， it seems like a cheating program. i change the game files

hack way will be banned.  maybe can use dma to send data to another pc.
最近地狱魅魔固定队伤害不够 很烦 想找个路子看秒伤

**Comment by qhhuang** [comment]
> oodle_state is in the lpk files, the xor key can be computed from connecting to the servers; shalzuth has a very messy implementation for both: https://github.com/shalzuth/LostArkDumper

LostArkDumper now cannot run normally and i find a same bug issue on https://github.com/shalzuth/LostArkDumper/issues/1
And where can i find  blowfish abd aes on LosDumper/Program.cs  on Line19 static void HardCodes
thank you

**Comment by SuYueQiuLiang** [comment]
> > oodle_state is in the lpk files, the xor key can be computed from connecting to the servers; shalzuth has a very messy implementation for both: https://github.com/shalzuth/LostArkDumper
> 
> LostArkDumper now cannot run normally and i find a same bug issue on [shalzuth/LostArkDumper#1](https://github.com/shalzuth/LostArkDumper/issues/1) And where can i find blowfish abd aes on LosDumper/Program.cs on Line19 static void HardCodes thank you

Is there any new progress? I also want to try this project recently.有联系方式吗，尝试合作一下？
